import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
  title: "Todo List",
  description: "Generated by BluMiin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="default">{children}</body>
    </html>
  );
}
